SQL_CONNECTION_STRING = "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-skthun-divingeval-prod.database.windows.net,1433;Database=sqldb-divingeval-prod;Uid=appsvc_user;Pwd=Qx7!Lm2@Tp4#Kc8Z;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"


ADMIN_PASSWORD = "IJSflk943$$493220-$+"