name: Supabase Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Täglich 2 Uhr UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Authenticate Supabase CLI
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: supabase login --access-token $SUPABASE_ACCESS_TOKEN

      - name: Dump database
        run: |
          supabase db dump --file=backup_$(date +%Y%m%d_%H%M%S).sql

      - name: Upload backup artifact
        uses: actions/upload-artifact@v2
        with:
          name: supabase-backup
          path: backup_*.sql
