name: Supabase Full Backup with CLI Tunnel

on:
  schedule:
    - cron: '0 2 * * *'  # täglich 2:00 UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install supabase CLI
        run: npm install -g supabase

      - name: Extract project ref
        run: |
          PROJECT_REF=$(echo $SUPABASE_URL | sed -E 's|https://([^.]+)\.supabase\.co|\1|')
          echo "PROJECT_REF=$PROJECT_REF" >> $GITHUB_ENV

      - name: Start Supabase DB Tunnel in background
        run: |
          supabase db tunnel --project-ref $PROJECT_REF --token $SUPABASE_KEY > tunnel.log 2>&1 &
          echo $! > supabase_tunnel.pid
          sleep 10
          echo "--- Tunnel Log ---"
          cat tunnel.log

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Backup database via tunnel
        run: |
          export PGPASSWORD=$SUPABASE_KEY
          pg_dump -h localhost -p 6543 -U postgres -d postgres --format=tar --file=backup_$(date +%Y%m%d_%H%M%S).tar

      - name: Upload backup artifact
        uses: actions/upload-artifact@v2
        with:
          name: supabase-backup
          path: backup_*.tar

      - name: Kill Supabase Tunnel
        run: |
          kill $(cat supabase_tunnel.pid) || true
