name: Supabase Backup

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract project ref from SUPABASE_URL
        id: extract
        run: |
          PROJECT_REF=$(echo "${SUPABASE_URL}" | sed -E 's|https://([^.]+)\.supabase\.co|\1|')
          echo "PROJECT_REF=$PROJECT_REF" >> $GITHUB_ENV
          echo "Project ref: $PROJECT_REF"

      - name: Download pg_tunnel binary
        run: |
          curl -L -o pg_tunnel https://github.com/supabase/cli/releases/download/v1.156.0/pg_tunnel-linux-amd64
          chmod +x pg_tunnel
          file pg_tunnel  # Sanity check: should say "ELF 64-bit..."

      - name: Start pg_tunnel
        run: |
          ./pg_tunnel \
            --project-ref=$PROJECT_REF \
            --db-url "postgres://postgres:${SUPABASE_KEY}@db.${PROJECT_REF}.supabase.co:5432/postgres" \
            > tunnel.log 2>&1 &
          echo $! > pg_tunnel.pid

          sleep 5
          echo "--- pg_tunnel log ---"
          cat tunnel.log || true

      - name: Run pg_dump
        run: |
          export PGPASSWORD="${SUPABASE_KEY}"
          pg_dump -h localhost -p 5432 -U postgres -d postgres \
            --no-password --format=tar \
            --file=backup_$(date +%Y%m%d_%H%M%S).tar

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: backup_*.tar
